### ISSUE TITLE
Profile functions are not available?

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#108] opened 2020-04-04 14:04 UTC
When I try to call `measure` it gives me an error.

I need a way to benchmark some functions.

**Comment by aminya** [comment] 2020-04-05 01:33
I got it working in the following example:
```ts
describe("Activation Benchmark", () => {
    it("should measure and log the time activation", async function () {

        // This makes the log visible again from the command line.
        spyOn(console, 'log').and.callThrough();

        await atom.packages.activatePackage("status-bar")
        console.log("\n Activation Benchmark Started")

        measure("Activation Time", async function activationBenchmark() {
                await atom.packages.activatePackage("indent-detective")
            }
        )
        console.log("\n Finished")
    })
})
```
It would be good if you add an example to the readme.

**Comment by UziTech** [comment] 2020-04-05 02:07
There is an example in the readme https://github.com/UziTech/atom-jasmine3-test-runner#profile

the tests pass with just `measure` and `profile`.
https://github.com/UziTech/atom-jasmine3-test-runner/blob/master/spec/spec-helper/profile-spec.js
`window.measure` or `global.measure` work as well.

**Comment by aminya** [comment] 2020-04-05 08:18
> 
> 
> There is an example in the readme [UziTech/atom-jasmine3-test-runner#profile](https://github.com/UziTech/atom-jasmine3-test-runner#profile)
> 

I meant a full working example. Without `spyOn(console...` that example doesn't work.

> the tests pass with just measure and profile.
> /spec/spec-helper/profile-spec.js@master
> window.measure or global.measure work as well.

I got it working. However, it is unkown to typescript because of lacking type declarations. Maybe we can those to the repository.

**Comment by UziTech** [comment] 2020-04-05 14:32
If you want the console to log the time you shouldn't need to spy on the console. What error are you getting if you don't spy on the console?

If you want to create a PR for the types of be happy to review it.. I'm not sure how that works since they are only available if `specHelper` is true or `profile` spec helper is true.

You should be able to add them manually to the linter/typescript (e.g  eslint `globals`)

**Comment by aminya** [comment] 2020-04-05 15:13
> 
> 
> If you want the console to log the time you shouldn't need to spy on the console. What error are you getting if you don't spy on the console?
> 

I don't get any errors regarding the output. I just don't see the output in the terminal. I run the tests from terminal.

> 
> If you want to create a PR for the types I'd be happy to review it.. I'm not sure how that works since they are only available if specHelper is true or profile spec helper is true.
> 
> You should be able to add them manually to the linter/typescript (e.g eslint globals)

Probably I can do that!

**Comment by UziTech** [comment] 2020-04-05 15:59
> I just don't see the output in the terminal.

Are you spying on `console.log` somewhere else in your code? It seems to work fine for me.

**Comment by UziTech** [comment] 2020-05-12 20:21
I'm going to close this as I am unable to reproduce it. Feel free to reopen if this is still an issue.

**Closed by UziTech** 2020-05-12 20:21 UTC
Labels: waiting for response
